<?php

namespace DoctrineProxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Incidente extends \App\Models\Entities\Incidente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'fechaApertura', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'fechaCierreGeneral', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'fechasDeCierre', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'resuelto', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'observaciones', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'prestacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'id', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'fechaApertura', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'fechaCierreGeneral', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'fechasDeCierre', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'resuelto', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'observaciones', '' . "\0" . 'App\\Models\\Entities\\Incidente' . "\0" . 'prestacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Incidente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaApertura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaApertura', []);

        return parent::getFechaApertura();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaApertura($fechaApertura): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaApertura', [$fechaApertura]);

        parent::setFechaApertura($fechaApertura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCierreGeneral()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCierreGeneral', []);

        return parent::getFechaCierreGeneral();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCierreGeneral($fechaCierreGeneral): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCierreGeneral', [$fechaCierreGeneral]);

        parent::setFechaCierreGeneral($fechaCierreGeneral);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechasDeCierre(): \Doctrine\Common\Collections\ArrayCollection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechasDeCierre', []);

        return parent::getFechasDeCierre();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechasDeCierre(\Doctrine\Common\Collections\ArrayCollection $fechasDeCierre): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechasDeCierre', [$fechasDeCierre]);

        parent::setFechasDeCierre($fechasDeCierre);
    }

    /**
     * {@inheritDoc}
     */
    public function getResuelto(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResuelto', []);

        return parent::getResuelto();
    }

    /**
     * {@inheritDoc}
     */
    public function setResuelto(bool $resuelto): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResuelto', [$resuelto]);

        parent::setResuelto($resuelto);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrestacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrestacion', []);

        return parent::getPrestacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrestacion($prestacion): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrestacion', [$prestacion]);

        parent::setPrestacion($prestacion);
    }

}
